#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 ("License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.zimbra.com/license
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is: Zimbra Collaboration Suite Server.
# 
# The Initial Developer of the Original Code is Zimbra, Inc.
# Portions created by Zimbra are Copyright (C) 2006 Zimbra, Inc.
# All Rights Reserved.
# 
# Contributor(s):
# 
# ***** END LICENSE BLOCK *****
# 
# Exit strings available are 17-31 with bits 5 and 6 set to 1.
# 16 = 112
# 17 = 113
# 18 = ... 
echo "Performing installation check"

for i in core mta store ldap snmp logger apache spell; do
	echo "Looking for $i"
	pkgs=`find /Library/Receipts/zimbra-${i}* -type d -maxdepth 0 | sort -r`
	first=1
	for pkg in $pkgs; do
    if [ -f "${pkg}/Contents/Info.plist" ]; then
      VER=`grep -C1 CFBundleGetInfoString ${pkg}/Contents/Info.plist | tail -1 | sed -e 's/\<[^>]*\>//g' -e 's/^ *//g' | awk -F, '{print $1}' | awk '{print $1}'`
    fi
		echo "Found $pkg $VER"
		if [ $first -ne 1 ]; then
			echo Removing $pkg
			/bin/rm -rf $pkg
		fi
		first=2
	done
done

exit 0
